{{- if .Values.profiseeRunTime.deployIngressRule }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profisee-ingress
  annotations:
    nginx.org/client-body-buffer-size: "512k"
    nginx.org/client-max-body-size: "0"

    nginx.org/proxy-buffering: "false"
    nginx.org/proxy-buffers: "32 512k"
    nginx.org/proxy-buffer-size: "512k"
    nginx.org/proxy-busy-buffers-size: "512k"
    
    nginx.org/proxy-connect-timeout: "5400s"
    nginx.org/proxy-read-timeout: "5400s"
    nginx.org/proxy-send-timeout: "5400s"
    nginx.org/websocket-services: "profisee-service"
    
    nginx.org/server-snippets: |
      client_header_buffer_size 512k;
      large_client_header_buffers 32 512k;
      proxy_request_buffering off;
      proxy_next_upstream off;
      {{ if .Values.profiseeRunTime.useLetsEncrypt }}
      set $redirect_https 1;
      if ($scheme = https) {
        set $redirect_https 0;
      }
      if ($request_uri ~* "^/\\.well-known/acme-challenge/") {
        set $redirect_https 0;
      }
      if ($redirect_https = 1) {
        return 301 https://$host$request_uri;
      }
      {{ end }}
    
    {{- if .Values.profiseeRunTime.useLetsEncrypt }}
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}

spec:
  ingressClassName: nginx
  {{- if .Values.profiseeRunTime.isPaaS }}
  tls:
  - hosts:
    - {{.Values.profiseeRunTime.externalDnsName}}
    secretName: profisee-tls-ingress
  {{- end }}  
  rules:
  - host: {{.Values.profiseeRunTime.externalDnsName}}
    http:
      paths:
      {{- if .Values.profiseeRunTime.isPaaS }}
      - path: /
      {{- else }}
      - path: /{{.Values.profiseeRunTime.webAppName}}
      {{- end }}
        pathType: Prefix
        backend:
          service:
            name: profisee-service
            port:
              number: 80
{{- end }}
