apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serviceaccount-rolebinding
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: profiseeserviceaccount
roleRef:
  kind: Role
  name: serviceaccount-role
  apiGroup: rbac.authorization.k8s.io
