{{- if eq .Values.integrations.governance.provider "alation" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: profisee-alation
data:
  ProfiseeAlationUrl: {{.Values.integrations.alation.url | b64enc | quote }}
  ProfiseeAlationUsername: {{.Values.integrations.alation.username | b64enc | quote }}
  ProfiseeAlationPassword: {{.Values.integrations.alation.password | b64enc | quote }}
{{- end }}
