{{- if .Values.cloud.azure.isProvider -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: profisee-fileshare
data:
  azurestorageaccountname: {{.Values.profiseeRunTime.fileRepository.accountName | b64enc }}
  azurestorageaccountkey: {{.Values.profiseeRunTime.fileRepository.password | b64enc }}
{{- end }}
