apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: profisee-filerepository-username
data:
  ProfiseeAttachmentRepositoryUserName: {{.Values.profiseeRunTime.fileRepository.userName | b64enc | quote}}
