{{- if eq .Values.integrations.governance.provider "azurePurview" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: profisee-purview
data:
  ProfiseePurviewTenantId: {{.Values.integrations.purview.tenantId | b64enc | quote }}
  ProfiseePurviewUrl: {{.Values.integrations.purview.url | b64enc | quote }}
  ProfiseePurviewCollectionId: {{.Values.integrations.purview.collectionId | b64enc | quote }}
  ProfiseePurviewClientId: {{.Values.integrations.purview.clientId | b64enc | quote }}
  ProfiseePurviewClientSecret: {{.Values.integrations.purview.clientSecret | b64enc | quote }}
{{- end }}
