apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: profisee
  labels:
    app: profisee
spec:
  selector:
    matchLabels:
      app: profisee
  serviceName: profisee-service
  replicas: {{.Values.profiseeRunTime.clusterNodeCount}}
  template:
    metadata:
      name: profisee
      labels:
        app: profisee
        {{- if .Values.cloud.azure.useManagedIdentity}}
        aadpodidbinding: {{.Values.cloud.azure.managedIdentity.name | lower}}
        {{- end}}
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: profiseeserviceaccount
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: profisee
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
      {{- if .Values.cloud.azure.isProvider }}
          {{ if hasSuffix "win22" .Values.image.tag }}
            "kubernetes.azure.com/os-sku": Windows2022
          {{ else }}
            "kubernetes.azure.com/os-sku": Windows2019
          {{ end }}
      {{- end }}
      {{- if .Values.cloud.aws.isProvider }}
          "kubernetes.io/os": windows
      {{- end }}
      volumes:
      - name: data-volume
        projected:
          sources:
          - secret:
              name: profisee-license
          - secret:
              name: profisee-oidcproviders
      - name: initscripts
        secret:
          secretName: profisee-initscripts
      {{- if .Values.cloud.azure.isProvider }}
      - name: fileshare
        csi:
          driver: file.csi.azure.com
          volumeAttributes:
            secretName: profisee-fileshare
            shareName: {{.Values.profiseeRunTime.fileRepository.fileShareName}}
      {{- end }}
      {{- if .Values.cloud.aws.isProvider }}
      - name: fileshare
        awsElasticBlockStore:
          volumeID: {{.Values.cloud.aws.ebsVolumeId}}
          fsType: ntfs
      {{- end }}
      {{- if .Values.cloud.google.isProvider }}
      - name: fileshare
        gcePersistentDisk:
          pdName: {{.Values.cloud.google.gceVolumeName}}
          fsType: ntfs
      {{- end }}
      dnsConfig:
        searches:
        - profisee-service.{{.Release.Namespace}}.svc.cluster.local
      containers:
      - name: profisee
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
              - powershell
              - >-
                if((Get-Service profisee).Status -ne 'Stopped'){return
                0}else{throw 'Profisee service is down'}
          initialDelaySeconds: 600
          timeoutSeconds: 5
          periodSeconds: 60
        lifecycle:
          postStart:
            exec:
              command:
                - powershell
                - >-
                  curl.exe -fsSL -o .\Fileshare\forensics_log_pull.ps1
                  "https://raw.githubusercontent.com/profisee/kubernetes/master/Azure-ARM/forensics_log_pull.ps1"
          preStop:
            exec:
              command:
                - powershell
                - .\Fileshare\forensics_log_pull.ps1
        volumeMounts:
        - name: data-volume
          mountPath: C:\data
          readOnly: true
        - name: initscripts
          mountPath: C:\scripts
        {{- if .Values.cloud.azure.isProvider }}
        - name: fileshare
          mountPath: c:\Fileshare
        {{- end }}
        {{- if .Values.cloud.aws.isProvider }}
        - name: fileshare
          mountPath: c:\Fileshare
        {{- end }}
        {{- if .Values.cloud.google.isProvider }}
        - name: fileshare
          mountPath: c:\Fileshare
        {{- end }}
        envFrom:
        - configMapRef:
            name: profisee-settings
        env:
        - name: ProfiseeSqlUserName
          valueFrom:
            secretKeyRef:
                name: profisee-sql-username
                key: ProfiseeSqlUserName
        - name: ProfiseeSqlPassword
          valueFrom:
            secretKeyRef:
                name: profisee-sql-password
                key: ProfiseeSqlPassword
        - name: ProfiseeAttachmentRepositoryUserName
          valueFrom:
            secretKeyRef:
                name: profisee-filerepository-username
                key: ProfiseeAttachmentRepositoryUserName
        - name: ProfiseeAttachmentRepositoryUserPassword
          valueFrom:
            secretKeyRef:
                name: profisee-filerepository-password
                key: ProfiseeAttachmentRepositoryUserPassword
        - name: ProfiseeOidcClientId
          valueFrom:
            secretKeyRef:
                name: profisee-oidc-clientid
                key: ProfiseeOidcClientId
        - name: ProfiseeOidcClientSecret
          valueFrom:
            secretKeyRef:
                name: profisee-oidc-secret
                key: ProfiseeOidcClientSecret
        {{- if .Values.cloud.azure.isProvider }}
        - name: ProfiseePurviewUrl
          valueFrom:
            secretKeyRef:
                name: profisee-purview
                key: ProfiseePurviewUrl
        - name: ProfiseePurviewCollectionId
          valueFrom:
            secretKeyRef:
                name: profisee-purview
                key: ProfiseePurviewCollectionId
        - name: ProfiseePurviewTenantId
          valueFrom:
            secretKeyRef:
                name: profisee-purview
                key: ProfiseePurviewTenantId
        - name: ProfiseePurviewClientId
          valueFrom:
            secretKeyRef:
                name: profisee-purview
                key: ProfiseePurviewClientId
        - name: ProfiseePurviewClientSecret
          valueFrom:
            secretKeyRef:
                name: profisee-purview
                key: ProfiseePurviewClientSecret
        {{- end }}
        resources:
          limits:
            cpu: {{.Values.clusterNode.limits.cpu}}
            memory: {{.Values.clusterNode.limits.memory}}
          requests:
            cpu: {{.Values.clusterNode.requests.cpu}}
            memory: {{.Values.clusterNode.requests.memory}}
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: profisee-containerregistry
