controller:
  ingressClass:
    name: nginx
    create: true
  enableCustomResources: false
  nginxplus: false
  enableSnippets: true
  config:
    entries:
      server-tokens: "false"
  nodeSelector:
    kubernetes.io/os: linux
  replicaCount: 1
  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    annotations:
      service.beta.kubernetes.io/port_80_health-probe_protocol: "Tcp"
      service.beta.kubernetes.io/port_443_health-probe_protocol: "Tcp"
