controller:
  ingressClass:
    name: nginx
    create: true
  enableCustomResources: false
  nginxplus: false
  enableSnippets: true
  config:
    entries:
      http-snippets: |
        client_header_buffer_size 512k;
        large_client_header_buffers 32 512k;
      location-snippets: |
        proxy_next_upstream off;
        proxy_request_buffering off;
      server-tokens: "false"
  nodeSelector:
    kubernetes.io/os: linux
  replicaCount: 1
  service:
    type: LoadBalancer
    externalTrafficPolicy: Cluster
    annotations:
      service.beta.kubernetes.io/port_80_health-probe_protocol: "Tcp"
      service.beta.kubernetes.io/port_443_health-probe_protocol: "Tcp"
